version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 1337:8000
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A core beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis